global:
  imageTag: replace-with-git-sha
  imagePullPolicy: Always

secrets:
  platformApiKeys: replace-me
  internalApiKey: replace-me

redis:
  storage: 5Gi

databases:
  incidents:
    password: replace-me
    storage: 10Gi
  alerts:
    password: replace-me
    storage: 10Gi
  oncall:
    password: replace-me
    storage: 10Gi
  statusPage:
    password: replace-me
    storage: 10Gi

