fail-on-severity: high
fail-on-scopes:
  - runtime
  - development
  - unknown
license-check: true
vulnerability-check: true
show-openssf-scorecard: true
show-patched-versions: true
allow-licenses:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MIT
  - MPL-2.0
  - PostgreSQL
  - Python-2.0
  - PSF-2.0
