apiVersion: v1
kind: Secret
metadata:
  name: platform-shared-secrets
  labels:
    app.kubernetes.io/part-of: incident-platform
type: Opaque
stringData:
  PLATFORM_API_KEYS: dev-platform-key
  INTERNAL_API_KEY: dev-platform-key
---
apiVersion: v1
kind: Secret
metadata:
  name: incidents-db-secrets
  labels:
    app.kubernetes.io/part-of: incident-platform
type: Opaque
stringData:
  POSTGRES_DB: incidents
  POSTGRES_USER: incidents
  POSTGRES_PASSWORD: incidents
  DATABASE_URL: postgresql+psycopg://incidents:incidents@postgres-incidents:5432/incidents
---
apiVersion: v1
kind: Secret
metadata:
  name: alerts-db-secrets
  labels:
    app.kubernetes.io/part-of: incident-platform
type: Opaque
stringData:
  POSTGRES_DB: alerts
  POSTGRES_USER: alerts
  POSTGRES_PASSWORD: alerts
  DATABASE_URL: postgresql+psycopg://alerts:alerts@postgres-alerts:5432/alerts
---
apiVersion: v1
kind: Secret
metadata:
  name: oncall-db-secrets
  labels:
    app.kubernetes.io/part-of: incident-platform
type: Opaque
stringData:
  POSTGRES_DB: oncall
  POSTGRES_USER: oncall
  POSTGRES_PASSWORD: oncall
  DATABASE_URL: postgresql+psycopg://oncall:oncall@postgres-oncall:5432/oncall
---
apiVersion: v1
kind: Secret
metadata:
  name: status-page-db-secrets
  labels:
    app.kubernetes.io/part-of: incident-platform
type: Opaque
stringData:
  POSTGRES_DB: status_page
  POSTGRES_USER: status_page
  POSTGRES_PASSWORD: status_page
  DATABASE_URL: postgresql+psycopg://status_page:status_page@postgres-status-page:5432/status_page

